### ISSUE TITLE
Color of outside map at Laurelia is green

### ISSUE THREAD

**Issue by sujiniku** [makrohn/polymorphable#102]
Only Laurelia map,, the outside of the map is green color. Therefore, it is difficult to understand that the map ends there.
Like other maps, the color of the outside of the map  should be black .

Also, the display message of the image location should be displayed only once. It should avoid redisplaying while displaying this message.

Also, I think,in POT file, there is not this message.

![screenshot from 2018-02-25 15-54-00](https://user-images.githubusercontent.com/26195610/36638946-6477467c-1a44-11e8-846b-41c72e8929e8.png)

**Comment by dorkster** [comment]
Fixed in 7f643b04b0ec78b536833f3c1d61d7ff36cdb2a5 and fa93b49d6738bead626e3c64eea8041958d267d7
