### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by doofus-01** [makrohn/polymorphable#110]
I was looking at starting a mod for flare, but 3D graphics with blender is more than I can deal with.  I can deal with pixel art, so I gave polymorphable a try.  Unfortunately, it quits if you left-click.

I also tried using the https://github.com/dorkster/flare-starter-pack as a starting point, but that has the same issue:  left-click or let the slime touch you, it quits.  Running from command-line gives the message in the title of this issue.

Empyrean Campaign works fine, I guess there might be some missing or obsolete parameter in one of the many *.txt files for polymorphable and starter, but I have no idea how to find it.

This is Flare 1.11 on SuSE Linux Leap 15.1, installed from the distribution.

EDIT: I forgot I had Developer Mode enabled.  Disabling that "fixes" the issue.  Lowers the priority, but surely this isn't intended behavior (and Empyrean Campaign still works fine in Developer mode)

**Comment by dorkster** [comment]
Thanks for the report (and for specifying that it happened in Dev Mode). This has been fixed upstream: https://github.com/flareteam/flare-engine/commit/cae6c35c27b4ea248e2d7edcf788fad5848d86ae

You can actually re-enable dev mode if you turn off the dev HUD. [Open the dev console](https://github.com/flareteam/flare-engine/wiki/Developer-Console) and enter `toggle_devhud` to turn the dev HUD off.
