### ISSUE TITLE
Unable to determine default font!

### ISSUE THREAD

**Issue by gabdab** [makrohn/polymorphable#86]
This is font.settings content (fonts present in fonts folder):
`# Only .ttf files are supported, due to limitations in SDL_ttf
# The font must be placed in /fonts
[font]
id=font_regular
style=default,DroidSansMono.ttf,12,1

[font]
id=font_bold
style=default,DroidSans-Bold.ttf,14,1

[font]
id=font_talker
style=default,DroidSans.ttf,13,1`

**Comment by dorkster** [comment]
The font setting syntax was changed in 2016 and we updated [the font_settings.txt here accordingly](https://github.com/makrohn/polymorphable/commit/2f204f99333cd03ebaff78163a76b68351a3b5c0#diff-e731178d9dcc91e6893a49b28ead5580). If you're using Flare 0.19, it won't work.
