### ISSUE TITLE
Quest Bug?

### ISSUE THREAD

**Issue by sujiniku** [makrohn/polymorphable#95]
In volcane, Even if the Hero use ghost talisman, she cannot go over lava. It will be game over.

Even if the player go to the west castle without defeating the huge skeleton of the volcanic boss, and if she defeats the huge ghost of the boss in the balcony of the castle, the boss will not drop half of the talisman and she cannot escape from the balcony.

**Comment by sujiniku** [comment]
This bug is not fixed.

![screenshot from 2018-02-25 12-46-06](https://user-images.githubusercontent.com/26195610/36637938-ea41b514-1a29-11e8-8265-958629d9ab8f.png)

**Comment by dorkster** [comment]
Try with https://github.com/makrohn/polymorphable/commit/645040c4016b5fcbb332304362e6b7dedb81bf43. It may have been possible that the min/max resist values weren't what they should be.
