### ISSUE TITLE
the transform bug

### ISSUE THREAD

**Issue by sujiniku** [makrohn/polymorphable#96]
Once transformed into a bat, the hero cannot return to her original form.
Because The command of action bar is not.

![screenshot from 2018-02-24 16-21-07pass](https://user-images.githubusercontent.com/26195610/36626953-5347be60-197f-11e8-9594-e9f5b5b9b6dc.png)

flare version  is 0.95 .
INFO: Flare 0.95 (Linux)

**Comment by dorkster** [comment]
Fixed: https://github.com/clintbellanger/flare-engine/commit/6095000b5fe6634985987129351d18899dcab988
